CREATE TABLE HOTEL
(
  ID BIGINT NOT NULL, 
  NAME CHARACTER VARYING(36) NOT NULL,
  RATING BIGINT,
  CONSTRAINT PRIMARY_KEY_HOTEL PRIMARY KEY (ID )
);

CREATE TABLE RATES
(
  HOTEL_ID BIGINT NOT NULL,   
  WEEKDAYRATES BIGINT,
  WEEKDAYRATESFORREWARDSMEMBERS BIGINT,
  WEEKENDRATES BIGINT,
  WEEKENDRATESFORREWARDSMEMBERS BIGINT,
  CONSTRAINT HOTEL_ID_ROW_FK FOREIGN KEY (HOTEL_ID)
      REFERENCES HOTEL (ID) 
);

CREATE TABLE ADDRESS
(
  HOTEL_ID BIGINT,
  ADDRESSLINE VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  ZIP VARCHAR,
  COUNTRY VARCHAR,
  CONSTRAINT ADDRESS_ROW_FK FOREIGN KEY (HOTEL_ID)
      REFERENCES HOTEL (ID) 
);

INSERT INTO HOTEL VALUES (1001, 'Lakewood HOTELS', 3);
INSERT INTO HOTEL VALUES (1002, 'Bridgewood HOTELS', 4);
INSERT INTO HOTEL VALUES (1003, 'Ridgewood HOTELS', 5);

INSERT INTO RATES VALUES (1001, 110, 80, 90, 80);
INSERT INTO RATES VALUES (1002, 160, 110, 60, 50);
INSERT INTO RATES VALUES (1003, 220, 100, 150, 40);

INSERT INTO ADDRESS VALUES (1001, '1111 1st St','Santa Monica','CA','90403','USA');
INSERT INTO ADDRESS VALUES (1002, '1112 2nd St','Santa Monica','CA','90403','USA');
INSERT INTO ADDRESS VALUES (1003, '1113 3rd St','Santa Monica','CA','90403','USA');